# Generated by Django 3.1.4 on 2020-12-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year_of_publication',
            field=models.CharField(max_length=5),
        ),
    ]
