# Generated by Django 3.1.4 on 2020-12-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rate', '0003_auto_20201211_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year_of_publication',
            field=models.CharField(max_length=4),
        ),
    ]
