# Generated by Django 3.1.4 on 2020-12-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rate', '0006_auto_20201213_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_of_publication',
            field=models.CharField(max_length=7),
        ),
    ]
