# Generated by Django 3.1.4 on 2020-12-15 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_rate', '0007_auto_20201213_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rate',
            new_name='score',
        ),
    ]
