# Generated by Django 3.1.4 on 2020-12-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_rate', '0008_auto_20201215_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='isbn',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='user_id',
            new_name='user',
        ),
    ]
