# Generated by Django 3.1.4 on 2020-12-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rate', '0009_auto_20201215_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mean_score',
            field=models.FloatField(default=0),
        ),
    ]
