# Generated by Django 3.1.4 on 2020-12-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rate', '0010_book_mean_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
