# Generated by Django 3.1.4 on 2020-12-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rate', '0013_auto_20201215_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='add_date',
            field=models.DateField(default='2020-12-16'),
        ),
        migrations.AlterField(
            model_name='user',
            name='add_date',
            field=models.DateField(default='2020-12-16'),
        ),
    ]
