# Generated by Django 3.1.4 on 2020-12-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rate', '0016_rate_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='book',
            name='add_date',
            field=models.DateField(default='2020-12-18'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='add_date',
            field=models.DateField(default='2020-12-18'),
        ),
        migrations.AlterField(
            model_name='user',
            name='add_date',
            field=models.DateField(default='2020-12-18'),
        ),
    ]
